spring:
  application:
    name: 'desafio-nubank'

  datasource:
    url: 'jdbc:postgresql://localhost:5432/ds-nubank'
    username: 'myuser'
    password: 'secret123buuu'
    driver-class-name: 'org.postgresql.Driver'

  jpa:
    database-platform: 'org.hibernate.dialect.PostgreSQLDialect'
    show-sql: true
    hibernate:
      ddl-auto: update