spring:
  application:
    name: 'desafio-nubank'

  datasource:
    url: 'jdbc:postgresql://localhost:5432/ds-nubank'
    username: 'myuser'
    password: 'secret123buuu'

    jpa:
      open-in-view: false
      hibernate:
        ddl-auto: 'update'
        show-sql: true
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'